version: '3.8'

services:
  cassandra:
    image: cassandra:4.1
    container_name: cassandra
    ports:
      - "9042:9042"   # CQL port
      - "9160:9160"   # Thrift port (optional/legacy)
    environment:
      - CASSANDRA_CLUSTER_NAME=${CASSANDRA_CLUSTER_NAME}
      - CASSANDRA_NUM_TOKENS=${CASSANDRA_NUM_TOKENS}
      - CASSANDRA_DC=${CASSANDRA_DC}
      - CASSANDRA_RACK=${CASSANDRA_RACK}
      - CASSANDRA_ENDPOINT_SNITCH=${CASSANDRA_ENDPOINT_SNITCH}
      - CASSANDRA_START_RPC=${CASSANDRA_START_RPC}
    volumes:
      - cassandra_data:/var/lib/cassandra

volumes:
  cassandra_data:
